//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the costmap_converter package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __costmap_converter__COSTMAPTOLINESDBSRANSACCONFIG_H__
#define __costmap_converter__COSTMAPTOLINESDBSRANSACCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace costmap_converter
{
  class CostmapToLinesDBSRANSACConfigStatics;

  class CostmapToLinesDBSRANSACConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(CostmapToLinesDBSRANSACConfig &config, const CostmapToLinesDBSRANSACConfig &max, const CostmapToLinesDBSRANSACConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CostmapToLinesDBSRANSACConfig &config1, const CostmapToLinesDBSRANSACConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CostmapToLinesDBSRANSACConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CostmapToLinesDBSRANSACConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CostmapToLinesDBSRANSACConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CostmapToLinesDBSRANSACConfig &config) const = 0;
      virtual void getValue(const CostmapToLinesDBSRANSACConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T CostmapToLinesDBSRANSACConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T CostmapToLinesDBSRANSACConfig::* field;

      virtual void clamp(CostmapToLinesDBSRANSACConfig &config, const CostmapToLinesDBSRANSACConfig &max, const CostmapToLinesDBSRANSACConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CostmapToLinesDBSRANSACConfig &config1, const CostmapToLinesDBSRANSACConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CostmapToLinesDBSRANSACConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CostmapToLinesDBSRANSACConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CostmapToLinesDBSRANSACConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CostmapToLinesDBSRANSACConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CostmapToLinesDBSRANSACConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CostmapToLinesDBSRANSACConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, CostmapToLinesDBSRANSACConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<CostmapToLinesDBSRANSACConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CostmapToLinesDBSRANSACConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("cluster_max_distance"==(*_i)->name){cluster_max_distance = boost::any_cast<double>(val);}
        if("cluster_min_pts"==(*_i)->name){cluster_min_pts = boost::any_cast<int>(val);}
        if("cluster_max_pts"==(*_i)->name){cluster_max_pts = boost::any_cast<int>(val);}
        if("ransac_inlier_distance"==(*_i)->name){ransac_inlier_distance = boost::any_cast<double>(val);}
        if("ransac_min_inliers"==(*_i)->name){ransac_min_inliers = boost::any_cast<int>(val);}
        if("ransac_no_iterations"==(*_i)->name){ransac_no_iterations = boost::any_cast<int>(val);}
        if("ransac_remainig_outliers"==(*_i)->name){ransac_remainig_outliers = boost::any_cast<int>(val);}
        if("ransac_convert_outlier_pts"==(*_i)->name){ransac_convert_outlier_pts = boost::any_cast<bool>(val);}
        if("ransac_filter_remaining_outlier_pts"==(*_i)->name){ransac_filter_remaining_outlier_pts = boost::any_cast<bool>(val);}
        if("convex_hull_min_pt_separation"==(*_i)->name){convex_hull_min_pt_separation = boost::any_cast<double>(val);}
      }
    }

    double cluster_max_distance;
int cluster_min_pts;
int cluster_max_pts;
double ransac_inlier_distance;
int ransac_min_inliers;
int ransac_no_iterations;
int ransac_remainig_outliers;
bool ransac_convert_outlier_pts;
bool ransac_filter_remaining_outlier_pts;
double convex_hull_min_pt_separation;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double cluster_max_distance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cluster_min_pts;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cluster_max_pts;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ransac_inlier_distance;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int ransac_min_inliers;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int ransac_no_iterations;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int ransac_remainig_outliers;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool ransac_convert_outlier_pts;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool ransac_filter_remaining_outlier_pts;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double convex_hull_min_pt_separation;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CostmapToLinesDBSRANSACConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CostmapToLinesDBSRANSACConfig &__max__ = __getMax__();
      const CostmapToLinesDBSRANSACConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CostmapToLinesDBSRANSACConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CostmapToLinesDBSRANSACConfig &__getDefault__();
    static const CostmapToLinesDBSRANSACConfig &__getMax__();
    static const CostmapToLinesDBSRANSACConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const CostmapToLinesDBSRANSACConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void CostmapToLinesDBSRANSACConfig::ParamDescription<std::string>::clamp(CostmapToLinesDBSRANSACConfig &config, const CostmapToLinesDBSRANSACConfig &max, const CostmapToLinesDBSRANSACConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class CostmapToLinesDBSRANSACConfigStatics
  {
    friend class CostmapToLinesDBSRANSACConfig;

    CostmapToLinesDBSRANSACConfigStatics()
    {
CostmapToLinesDBSRANSACConfig::GroupDescription<CostmapToLinesDBSRANSACConfig::DEFAULT, CostmapToLinesDBSRANSACConfig> Default("Default", "", 0, 0, true, &CostmapToLinesDBSRANSACConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cluster_max_distance = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cluster_max_distance = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cluster_max_distance = 0.4;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<double>("cluster_max_distance", "double", 0, "Parameter for DB_Scan, maximum distance to neighbors [m]", "", &CostmapToLinesDBSRANSACConfig::cluster_max_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<double>("cluster_max_distance", "double", 0, "Parameter for DB_Scan, maximum distance to neighbors [m]", "", &CostmapToLinesDBSRANSACConfig::cluster_max_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cluster_min_pts = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cluster_min_pts = 20;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cluster_min_pts = 2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("cluster_min_pts", "int", 0, "Parameter for DB_Scan: minimum number of points that define a cluster", "", &CostmapToLinesDBSRANSACConfig::cluster_min_pts)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("cluster_min_pts", "int", 0, "Parameter for DB_Scan: minimum number of points that define a cluster", "", &CostmapToLinesDBSRANSACConfig::cluster_min_pts)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cluster_max_pts = 2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cluster_max_pts = 200;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cluster_max_pts = 30;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("cluster_max_pts", "int", 0, "Parameter for DB_Scan: maximum number of points that define a cluster (limit cluster size to avoid large L- and U-shapes)", "", &CostmapToLinesDBSRANSACConfig::cluster_max_pts)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("cluster_max_pts", "int", 0, "Parameter for DB_Scan: maximum number of points that define a cluster (limit cluster size to avoid large L- and U-shapes)", "", &CostmapToLinesDBSRANSACConfig::cluster_max_pts)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ransac_inlier_distance = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ransac_inlier_distance = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ransac_inlier_distance = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<double>("ransac_inlier_distance", "double", 0, "Maximum distance to the line segment for inliers", "", &CostmapToLinesDBSRANSACConfig::ransac_inlier_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<double>("ransac_inlier_distance", "double", 0, "Maximum distance to the line segment for inliers", "", &CostmapToLinesDBSRANSACConfig::ransac_inlier_distance)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ransac_min_inliers = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ransac_min_inliers = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ransac_min_inliers = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("ransac_min_inliers", "int", 0, "Minimum numer of inliers required to form a line", "", &CostmapToLinesDBSRANSACConfig::ransac_min_inliers)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("ransac_min_inliers", "int", 0, "Minimum numer of inliers required to form a line", "", &CostmapToLinesDBSRANSACConfig::ransac_min_inliers)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ransac_no_iterations = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ransac_no_iterations = 10000;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ransac_no_iterations = 2000;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("ransac_no_iterations", "int", 0, "Number of ransac iterations", "", &CostmapToLinesDBSRANSACConfig::ransac_no_iterations)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("ransac_no_iterations", "int", 0, "Number of ransac iterations", "", &CostmapToLinesDBSRANSACConfig::ransac_no_iterations)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ransac_remainig_outliers = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ransac_remainig_outliers = 50;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ransac_remainig_outliers = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("ransac_remainig_outliers", "int", 0, "Repeat ransac until the number of outliers is as specified here", "", &CostmapToLinesDBSRANSACConfig::ransac_remainig_outliers)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<int>("ransac_remainig_outliers", "int", 0, "Repeat ransac until the number of outliers is as specified here", "", &CostmapToLinesDBSRANSACConfig::ransac_remainig_outliers)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ransac_convert_outlier_pts = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ransac_convert_outlier_pts = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ransac_convert_outlier_pts = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<bool>("ransac_convert_outlier_pts", "bool", 0, "Convert remaining outliers to single points.", "", &CostmapToLinesDBSRANSACConfig::ransac_convert_outlier_pts)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<bool>("ransac_convert_outlier_pts", "bool", 0, "Convert remaining outliers to single points.", "", &CostmapToLinesDBSRANSACConfig::ransac_convert_outlier_pts)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ransac_filter_remaining_outlier_pts = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ransac_filter_remaining_outlier_pts = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ransac_filter_remaining_outlier_pts = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<bool>("ransac_filter_remaining_outlier_pts", "bool", 0, "Filter the interior of remaining outliers and keep only keypoints of their convex hull", "", &CostmapToLinesDBSRANSACConfig::ransac_filter_remaining_outlier_pts)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<bool>("ransac_filter_remaining_outlier_pts", "bool", 0, "Filter the interior of remaining outliers and keep only keypoints of their convex hull", "", &CostmapToLinesDBSRANSACConfig::ransac_filter_remaining_outlier_pts)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.convex_hull_min_pt_separation = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.convex_hull_min_pt_separation = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.convex_hull_min_pt_separation = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<double>("convex_hull_min_pt_separation", "double", 0, "Clear keypoints of the convex polygon that are close to each other [distance in meters] (0: keep all)", "", &CostmapToLinesDBSRANSACConfig::convex_hull_min_pt_separation)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::ParamDescription<double>("convex_hull_min_pt_separation", "double", 0, "Clear keypoints of the convex polygon that are close to each other [distance in meters] (0: keep all)", "", &CostmapToLinesDBSRANSACConfig::convex_hull_min_pt_separation)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(CostmapToLinesDBSRANSACConfig::AbstractGroupDescriptionConstPtr(new CostmapToLinesDBSRANSACConfig::GroupDescription<CostmapToLinesDBSRANSACConfig::DEFAULT, CostmapToLinesDBSRANSACConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<CostmapToLinesDBSRANSACConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CostmapToLinesDBSRANSACConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CostmapToLinesDBSRANSACConfig __max__;
    CostmapToLinesDBSRANSACConfig __min__;
    CostmapToLinesDBSRANSACConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CostmapToLinesDBSRANSACConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CostmapToLinesDBSRANSACConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CostmapToLinesDBSRANSACConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const CostmapToLinesDBSRANSACConfig &CostmapToLinesDBSRANSACConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const CostmapToLinesDBSRANSACConfig &CostmapToLinesDBSRANSACConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const CostmapToLinesDBSRANSACConfig &CostmapToLinesDBSRANSACConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<CostmapToLinesDBSRANSACConfig::AbstractParamDescriptionConstPtr> &CostmapToLinesDBSRANSACConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CostmapToLinesDBSRANSACConfig::AbstractGroupDescriptionConstPtr> &CostmapToLinesDBSRANSACConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CostmapToLinesDBSRANSACConfigStatics *CostmapToLinesDBSRANSACConfig::__get_statics__()
  {
    const static CostmapToLinesDBSRANSACConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CostmapToLinesDBSRANSACConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __COSTMAPTOLINESDBSRANSACRECONFIGURATOR_H__
