TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.28
  min_vel_x: 0.08
  escape_vel: -0.10
  max_vel_theta:  0.8
  min_vel_theta:  0.1
  max_rotation_vel: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.2

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05
