global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 0.01
  publish_frequency: 0.05
  static_map: true

  rolling_window: false
  transform_tolerance: 0.5

  plugins:
#  - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
