#base_global_planner: global_planner/VdGlobalPlanner
# base_local_planner: teb_local_planner/TebLocalPlannerROS
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 30.0

planner_frequency: 0.0
planner_patience: 15.0

oscillation_timeout: 10.0
oscillation_distance: 0.3

conservative_reset_dist: 0.2 #distance from an obstacle at which it will unstuck itself
