//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the costmap_converter package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __costmap_converter__COSTMAPTODYNAMICOBSTACLESCONFIG_H__
#define __costmap_converter__COSTMAPTODYNAMICOBSTACLESCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace costmap_converter
{
  class CostmapToDynamicObstaclesConfigStatics;

  class CostmapToDynamicObstaclesConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(CostmapToDynamicObstaclesConfig &config, const CostmapToDynamicObstaclesConfig &max, const CostmapToDynamicObstaclesConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CostmapToDynamicObstaclesConfig &config1, const CostmapToDynamicObstaclesConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CostmapToDynamicObstaclesConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CostmapToDynamicObstaclesConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CostmapToDynamicObstaclesConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CostmapToDynamicObstaclesConfig &config) const = 0;
      virtual void getValue(const CostmapToDynamicObstaclesConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T CostmapToDynamicObstaclesConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T CostmapToDynamicObstaclesConfig::* field;

      virtual void clamp(CostmapToDynamicObstaclesConfig &config, const CostmapToDynamicObstaclesConfig &max, const CostmapToDynamicObstaclesConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CostmapToDynamicObstaclesConfig &config1, const CostmapToDynamicObstaclesConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CostmapToDynamicObstaclesConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CostmapToDynamicObstaclesConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CostmapToDynamicObstaclesConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CostmapToDynamicObstaclesConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CostmapToDynamicObstaclesConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CostmapToDynamicObstaclesConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, CostmapToDynamicObstaclesConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<CostmapToDynamicObstaclesConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CostmapToDynamicObstaclesConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("alpha_slow"==(*_i)->name){alpha_slow = boost::any_cast<double>(val);}
        if("alpha_fast"==(*_i)->name){alpha_fast = boost::any_cast<double>(val);}
        if("beta"==(*_i)->name){beta = boost::any_cast<double>(val);}
        if("min_sep_between_slow_and_fast_filter"==(*_i)->name){min_sep_between_slow_and_fast_filter = boost::any_cast<int>(val);}
        if("min_occupancy_probability"==(*_i)->name){min_occupancy_probability = boost::any_cast<int>(val);}
        if("max_occupancy_neighbors"==(*_i)->name){max_occupancy_neighbors = boost::any_cast<int>(val);}
        if("morph_size"==(*_i)->name){morph_size = boost::any_cast<int>(val);}
        if("publish_static_obstacles"==(*_i)->name){publish_static_obstacles = boost::any_cast<bool>(val);}
        if("min_distance_between_blobs"==(*_i)->name){min_distance_between_blobs = boost::any_cast<double>(val);}
        if("filter_by_area"==(*_i)->name){filter_by_area = boost::any_cast<bool>(val);}
        if("min_area"==(*_i)->name){min_area = boost::any_cast<int>(val);}
        if("max_area"==(*_i)->name){max_area = boost::any_cast<int>(val);}
        if("filter_by_circularity"==(*_i)->name){filter_by_circularity = boost::any_cast<bool>(val);}
        if("min_circularity"==(*_i)->name){min_circularity = boost::any_cast<double>(val);}
        if("max_circularity"==(*_i)->name){max_circularity = boost::any_cast<double>(val);}
        if("filter_by_inertia"==(*_i)->name){filter_by_inertia = boost::any_cast<bool>(val);}
        if("min_inertia_ratio"==(*_i)->name){min_inertia_ratio = boost::any_cast<double>(val);}
        if("max_inertia_ratio"==(*_i)->name){max_inertia_ratio = boost::any_cast<double>(val);}
        if("filter_by_convexity"==(*_i)->name){filter_by_convexity = boost::any_cast<bool>(val);}
        if("min_convexity"==(*_i)->name){min_convexity = boost::any_cast<double>(val);}
        if("max_convexity"==(*_i)->name){max_convexity = boost::any_cast<double>(val);}
        if("dt"==(*_i)->name){dt = boost::any_cast<double>(val);}
        if("dist_thresh"==(*_i)->name){dist_thresh = boost::any_cast<double>(val);}
        if("max_allowed_skipped_frames"==(*_i)->name){max_allowed_skipped_frames = boost::any_cast<int>(val);}
        if("max_trace_length"==(*_i)->name){max_trace_length = boost::any_cast<int>(val);}
      }
    }

    double alpha_slow;
double alpha_fast;
double beta;
int min_sep_between_slow_and_fast_filter;
int min_occupancy_probability;
int max_occupancy_neighbors;
int morph_size;
bool publish_static_obstacles;
double min_distance_between_blobs;
bool filter_by_area;
int min_area;
int max_area;
bool filter_by_circularity;
double min_circularity;
double max_circularity;
bool filter_by_inertia;
double min_inertia_ratio;
double max_inertia_ratio;
bool filter_by_convexity;
double min_convexity;
double max_convexity;
double dt;
double dist_thresh;
int max_allowed_skipped_frames;
int max_trace_length;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double alpha_slow;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double alpha_fast;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double beta;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_sep_between_slow_and_fast_filter;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_occupancy_probability;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_occupancy_neighbors;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int morph_size;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool publish_static_obstacles;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_distance_between_blobs;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool filter_by_area;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_area;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_area;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool filter_by_circularity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_circularity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_circularity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool filter_by_inertia;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_inertia_ratio;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_inertia_ratio;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool filter_by_convexity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_convexity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_convexity;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dt;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dist_thresh;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_allowed_skipped_frames;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int max_trace_length;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CostmapToDynamicObstaclesConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CostmapToDynamicObstaclesConfig &__max__ = __getMax__();
      const CostmapToDynamicObstaclesConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CostmapToDynamicObstaclesConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CostmapToDynamicObstaclesConfig &__getDefault__();
    static const CostmapToDynamicObstaclesConfig &__getMax__();
    static const CostmapToDynamicObstaclesConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const CostmapToDynamicObstaclesConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void CostmapToDynamicObstaclesConfig::ParamDescription<std::string>::clamp(CostmapToDynamicObstaclesConfig &config, const CostmapToDynamicObstaclesConfig &max, const CostmapToDynamicObstaclesConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class CostmapToDynamicObstaclesConfigStatics
  {
    friend class CostmapToDynamicObstaclesConfig;

    CostmapToDynamicObstaclesConfigStatics()
    {
CostmapToDynamicObstaclesConfig::GroupDescription<CostmapToDynamicObstaclesConfig::DEFAULT, CostmapToDynamicObstaclesConfig> Default("Default", "", 0, 0, true, &CostmapToDynamicObstaclesConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.alpha_slow = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.alpha_slow = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.alpha_slow = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("alpha_slow", "double", 0, "Foreground detection: Learning rate of the slow filter", "", &CostmapToDynamicObstaclesConfig::alpha_slow)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("alpha_slow", "double", 0, "Foreground detection: Learning rate of the slow filter", "", &CostmapToDynamicObstaclesConfig::alpha_slow)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.alpha_fast = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.alpha_fast = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.alpha_fast = 0.85;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("alpha_fast", "double", 0, "Foreground detection: Learning rate of the fast filter", "", &CostmapToDynamicObstaclesConfig::alpha_fast)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("alpha_fast", "double", 0, "Foreground detection: Learning rate of the fast filter", "", &CostmapToDynamicObstaclesConfig::alpha_fast)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.beta = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.beta = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.beta = 0.85;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("beta", "double", 0, "Foreground detection: Weighting coefficient between a pixels value and the mean of its nearest neighbors", "", &CostmapToDynamicObstaclesConfig::beta)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("beta", "double", 0, "Foreground detection: Weighting coefficient between a pixels value and the mean of its nearest neighbors", "", &CostmapToDynamicObstaclesConfig::beta)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_sep_between_slow_and_fast_filter = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_sep_between_slow_and_fast_filter = 255;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_sep_between_slow_and_fast_filter = 80;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("min_sep_between_slow_and_fast_filter", "int", 0, "Foreground detection: Minimal difference between the fast and the slow filter to recognize a obstacle as dynamic", "", &CostmapToDynamicObstaclesConfig::min_sep_between_slow_and_fast_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("min_sep_between_slow_and_fast_filter", "int", 0, "Foreground detection: Minimal difference between the fast and the slow filter to recognize a obstacle as dynamic", "", &CostmapToDynamicObstaclesConfig::min_sep_between_slow_and_fast_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_occupancy_probability = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_occupancy_probability = 255;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_occupancy_probability = 180;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("min_occupancy_probability", "int", 0, "Foreground detection: Minimal value of the fast filter to recognize a obstacle as dynamic", "", &CostmapToDynamicObstaclesConfig::min_occupancy_probability)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("min_occupancy_probability", "int", 0, "Foreground detection: Minimal value of the fast filter to recognize a obstacle as dynamic", "", &CostmapToDynamicObstaclesConfig::min_occupancy_probability)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_occupancy_neighbors = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_occupancy_neighbors = 255;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_occupancy_neighbors = 80;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("max_occupancy_neighbors", "int", 0, "Foreground detection: Maximal mean value of the nearest neighbors of a pixel in the slow filter", "", &CostmapToDynamicObstaclesConfig::max_occupancy_neighbors)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("max_occupancy_neighbors", "int", 0, "Foreground detection: Maximal mean value of the nearest neighbors of a pixel in the slow filter", "", &CostmapToDynamicObstaclesConfig::max_occupancy_neighbors)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.morph_size = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.morph_size = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.morph_size = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("morph_size", "int", 0, "Foreground detection: Size of the structuring element for the closing operation", "", &CostmapToDynamicObstaclesConfig::morph_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("morph_size", "int", 0, "Foreground detection: Size of the structuring element for the closing operation", "", &CostmapToDynamicObstaclesConfig::morph_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publish_static_obstacles = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publish_static_obstacles = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publish_static_obstacles = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("publish_static_obstacles", "bool", 0, "Include static obstacles as single-point polygons", "", &CostmapToDynamicObstaclesConfig::publish_static_obstacles)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("publish_static_obstacles", "bool", 0, "Include static obstacles as single-point polygons", "", &CostmapToDynamicObstaclesConfig::publish_static_obstacles)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_distance_between_blobs = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_distance_between_blobs = 300.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_distance_between_blobs = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("min_distance_between_blobs", "double", 0, "Blob detection: Minimal distance between centers of two blobs to be considered as seperate blobs", "", &CostmapToDynamicObstaclesConfig::min_distance_between_blobs)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("min_distance_between_blobs", "double", 0, "Blob detection: Minimal distance between centers of two blobs to be considered as seperate blobs", "", &CostmapToDynamicObstaclesConfig::min_distance_between_blobs)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.filter_by_area = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.filter_by_area = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.filter_by_area = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("filter_by_area", "bool", 0, "Blob detection: Filter blobs based on number of pixels", "", &CostmapToDynamicObstaclesConfig::filter_by_area)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("filter_by_area", "bool", 0, "Blob detection: Filter blobs based on number of pixels", "", &CostmapToDynamicObstaclesConfig::filter_by_area)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_area = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_area = 300;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_area = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("min_area", "int", 0, "Blob detection: Minimal number of pixels a blob consists of", "", &CostmapToDynamicObstaclesConfig::min_area)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("min_area", "int", 0, "Blob detection: Minimal number of pixels a blob consists of", "", &CostmapToDynamicObstaclesConfig::min_area)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_area = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_area = 300;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_area = 300;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("max_area", "int", 0, "Blob detection: Maximal number of pixels a blob consists of", "", &CostmapToDynamicObstaclesConfig::max_area)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("max_area", "int", 0, "Blob detection: Maximal number of pixels a blob consists of", "", &CostmapToDynamicObstaclesConfig::max_area)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.filter_by_circularity = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.filter_by_circularity = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.filter_by_circularity = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("filter_by_circularity", "bool", 0, "Blob detection: Filter blobs based on their circularity", "", &CostmapToDynamicObstaclesConfig::filter_by_circularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("filter_by_circularity", "bool", 0, "Blob detection: Filter blobs based on their circularity", "", &CostmapToDynamicObstaclesConfig::filter_by_circularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_circularity = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_circularity = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_circularity = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("min_circularity", "double", 0, "Blob detection: Minimal circularity value (0 in case of a line)", "", &CostmapToDynamicObstaclesConfig::min_circularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("min_circularity", "double", 0, "Blob detection: Minimal circularity value (0 in case of a line)", "", &CostmapToDynamicObstaclesConfig::min_circularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_circularity = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_circularity = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_circularity = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("max_circularity", "double", 0, "Blob detection: Maximal circularity value (1 in case of a circle)", "", &CostmapToDynamicObstaclesConfig::max_circularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("max_circularity", "double", 0, "Blob detection: Maximal circularity value (1 in case of a circle)", "", &CostmapToDynamicObstaclesConfig::max_circularity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.filter_by_inertia = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.filter_by_inertia = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.filter_by_inertia = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("filter_by_inertia", "bool", 0, "Blob detection: Filter blobs based on their inertia ratio", "", &CostmapToDynamicObstaclesConfig::filter_by_inertia)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("filter_by_inertia", "bool", 0, "Blob detection: Filter blobs based on their inertia ratio", "", &CostmapToDynamicObstaclesConfig::filter_by_inertia)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_inertia_ratio = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_inertia_ratio = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_inertia_ratio = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("min_inertia_ratio", "double", 0, "Blob detection: Minimal inertia ratio", "", &CostmapToDynamicObstaclesConfig::min_inertia_ratio)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("min_inertia_ratio", "double", 0, "Blob detection: Minimal inertia ratio", "", &CostmapToDynamicObstaclesConfig::min_inertia_ratio)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_inertia_ratio = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_inertia_ratio = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_inertia_ratio = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("max_inertia_ratio", "double", 0, "Blob detection: Maximal inertia ratio", "", &CostmapToDynamicObstaclesConfig::max_inertia_ratio)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("max_inertia_ratio", "double", 0, "Blob detection: Maximal inertia ratio", "", &CostmapToDynamicObstaclesConfig::max_inertia_ratio)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.filter_by_convexity = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.filter_by_convexity = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.filter_by_convexity = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("filter_by_convexity", "bool", 0, "Blob detection: Filter blobs based on their convexity (Blob area / area of its convex hull)", "", &CostmapToDynamicObstaclesConfig::filter_by_convexity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<bool>("filter_by_convexity", "bool", 0, "Blob detection: Filter blobs based on their convexity (Blob area / area of its convex hull)", "", &CostmapToDynamicObstaclesConfig::filter_by_convexity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_convexity = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_convexity = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_convexity = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("min_convexity", "double", 0, "Blob detection: Minimum convexity ratio", "", &CostmapToDynamicObstaclesConfig::min_convexity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("min_convexity", "double", 0, "Blob detection: Minimum convexity ratio", "", &CostmapToDynamicObstaclesConfig::min_convexity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_convexity = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_convexity = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_convexity = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("max_convexity", "double", 0, "Blob detection: Maximal convexity ratio", "", &CostmapToDynamicObstaclesConfig::max_convexity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("max_convexity", "double", 0, "Blob detection: Maximal convexity ratio", "", &CostmapToDynamicObstaclesConfig::max_convexity)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dt = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dt = 3.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dt = 0.2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("dt", "double", 0, "Tracking: Time for one timestep of the kalman filter", "", &CostmapToDynamicObstaclesConfig::dt)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("dt", "double", 0, "Tracking: Time for one timestep of the kalman filter", "", &CostmapToDynamicObstaclesConfig::dt)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dist_thresh = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dist_thresh = 150.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dist_thresh = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("dist_thresh", "double", 0, "Tracking: Maximum distance between two points to be considered in the assignment problem", "", &CostmapToDynamicObstaclesConfig::dist_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<double>("dist_thresh", "double", 0, "Tracking: Maximum distance between two points to be considered in the assignment problem", "", &CostmapToDynamicObstaclesConfig::dist_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_allowed_skipped_frames = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_allowed_skipped_frames = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_allowed_skipped_frames = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("max_allowed_skipped_frames", "int", 0, "Tracking: Maximum number of frames a object is tracked while it is not seen", "", &CostmapToDynamicObstaclesConfig::max_allowed_skipped_frames)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("max_allowed_skipped_frames", "int", 0, "Tracking: Maximum number of frames a object is tracked while it is not seen", "", &CostmapToDynamicObstaclesConfig::max_allowed_skipped_frames)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_trace_length = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_trace_length = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_trace_length = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("max_trace_length", "int", 0, "Tracking: Maximum number of Points in a objects trace", "", &CostmapToDynamicObstaclesConfig::max_trace_length)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::ParamDescription<int>("max_trace_length", "int", 0, "Tracking: Maximum number of Points in a objects trace", "", &CostmapToDynamicObstaclesConfig::max_trace_length)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(CostmapToDynamicObstaclesConfig::AbstractGroupDescriptionConstPtr(new CostmapToDynamicObstaclesConfig::GroupDescription<CostmapToDynamicObstaclesConfig::DEFAULT, CostmapToDynamicObstaclesConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<CostmapToDynamicObstaclesConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CostmapToDynamicObstaclesConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CostmapToDynamicObstaclesConfig __max__;
    CostmapToDynamicObstaclesConfig __min__;
    CostmapToDynamicObstaclesConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CostmapToDynamicObstaclesConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CostmapToDynamicObstaclesConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CostmapToDynamicObstaclesConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const CostmapToDynamicObstaclesConfig &CostmapToDynamicObstaclesConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const CostmapToDynamicObstaclesConfig &CostmapToDynamicObstaclesConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const CostmapToDynamicObstaclesConfig &CostmapToDynamicObstaclesConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<CostmapToDynamicObstaclesConfig::AbstractParamDescriptionConstPtr> &CostmapToDynamicObstaclesConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CostmapToDynamicObstaclesConfig::AbstractGroupDescriptionConstPtr> &CostmapToDynamicObstaclesConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CostmapToDynamicObstaclesConfigStatics *CostmapToDynamicObstaclesConfig::__get_statics__()
  {
    const static CostmapToDynamicObstaclesConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CostmapToDynamicObstaclesConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __COSTMAPTODYNAMICOBSTACLESRECONFIGURATOR_H__
