// Generated by gencpp from file tutorial_action/DoDishesFeedback.msg
// DO NOT EDIT!


#ifndef TUTORIAL_ACTION_MESSAGE_DODISHESFEEDBACK_H
#define TUTORIAL_ACTION_MESSAGE_DODISHESFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_action
{
template <class ContainerAllocator>
struct DoDishesFeedback_
{
  typedef DoDishesFeedback_<ContainerAllocator> Type;

  DoDishesFeedback_()
    : pecent_complete(0)  {
    }
  DoDishesFeedback_(const ContainerAllocator& _alloc)
    : pecent_complete(0)  {
  (void)_alloc;
    }



   typedef uint32_t _pecent_complete_type;
  _pecent_complete_type pecent_complete;





  typedef boost::shared_ptr< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DoDishesFeedback_

typedef ::tutorial_action::DoDishesFeedback_<std::allocator<void> > DoDishesFeedback;

typedef boost::shared_ptr< ::tutorial_action::DoDishesFeedback > DoDishesFeedbackPtr;
typedef boost::shared_ptr< ::tutorial_action::DoDishesFeedback const> DoDishesFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_action::DoDishesFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_action::DoDishesFeedback_<ContainerAllocator1> & lhs, const ::tutorial_action::DoDishesFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.pecent_complete == rhs.pecent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_action::DoDishesFeedback_<ContainerAllocator1> & lhs, const ::tutorial_action::DoDishesFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfd0cf17f480a4264705c30ba0914c92";
  }

  static const char* value(const ::tutorial_action::DoDishesFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfd0cf17f480a426ULL;
  static const uint64_t static_value2 = 0x4705c30ba0914c92ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_action/DoDishesFeedback";
  }

  static const char* value(const ::tutorial_action::DoDishesFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"uint32 pecent_complete\n"
;
  }

  static const char* value(const ::tutorial_action::DoDishesFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pecent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoDishesFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_action::DoDishesFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_action::DoDishesFeedback_<ContainerAllocator>& v)
  {
    s << indent << "pecent_complete: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pecent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_ACTION_MESSAGE_DODISHESFEEDBACK_H
