// Generated by gencpp from file tutorial_action/DoDishesGoal.msg
// DO NOT EDIT!


#ifndef TUTORIAL_ACTION_MESSAGE_DODISHESGOAL_H
#define TUTORIAL_ACTION_MESSAGE_DODISHESGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_action
{
template <class ContainerAllocator>
struct DoDishesGoal_
{
  typedef DoDishesGoal_<ContainerAllocator> Type;

  DoDishesGoal_()
    : dish_id(0)  {
    }
  DoDishesGoal_(const ContainerAllocator& _alloc)
    : dish_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _dish_id_type;
  _dish_id_type dish_id;





  typedef boost::shared_ptr< ::tutorial_action::DoDishesGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_action::DoDishesGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DoDishesGoal_

typedef ::tutorial_action::DoDishesGoal_<std::allocator<void> > DoDishesGoal;

typedef boost::shared_ptr< ::tutorial_action::DoDishesGoal > DoDishesGoalPtr;
typedef boost::shared_ptr< ::tutorial_action::DoDishesGoal const> DoDishesGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_action::DoDishesGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_action::DoDishesGoal_<ContainerAllocator1> & lhs, const ::tutorial_action::DoDishesGoal_<ContainerAllocator2> & rhs)
{
  return lhs.dish_id == rhs.dish_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_action::DoDishesGoal_<ContainerAllocator1> & lhs, const ::tutorial_action::DoDishesGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_action::DoDishesGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_action::DoDishesGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_action::DoDishesGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a81404058645381c12ea9d0f83626d6";
  }

  static const char* value(const ::tutorial_action::DoDishesGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a81404058645381ULL;
  static const uint64_t static_value2 = 0xc12ea9d0f83626d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_action/DoDishesGoal";
  }

  static const char* value(const ::tutorial_action::DoDishesGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"uint32 dish_id\n"
;
  }

  static const char* value(const ::tutorial_action::DoDishesGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dish_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoDishesGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_action::DoDishesGoal_<ContainerAllocator>& v)
  {
    s << indent << "dish_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dish_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_ACTION_MESSAGE_DODISHESGOAL_H
