// Generated by gencpp from file tutorial_action/DoDishesActionGoal.msg
// DO NOT EDIT!


#ifndef TUTORIAL_ACTION_MESSAGE_DODISHESACTIONGOAL_H
#define TUTORIAL_ACTION_MESSAGE_DODISHESACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <tutorial_action/DoDishesGoal.h>

namespace tutorial_action
{
template <class ContainerAllocator>
struct DoDishesActionGoal_
{
  typedef DoDishesActionGoal_<ContainerAllocator> Type;

  DoDishesActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  DoDishesActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::tutorial_action::DoDishesGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DoDishesActionGoal_

typedef ::tutorial_action::DoDishesActionGoal_<std::allocator<void> > DoDishesActionGoal;

typedef boost::shared_ptr< ::tutorial_action::DoDishesActionGoal > DoDishesActionGoalPtr;
typedef boost::shared_ptr< ::tutorial_action::DoDishesActionGoal const> DoDishesActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator1> & lhs, const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator1> & lhs, const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7437cf188adf3845da5f85aeb996ad39";
  }

  static const char* value(const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7437cf188adf3845ULL;
  static const uint64_t static_value2 = 0xda5f85aeb996ad39ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_action/DoDishesActionGoal";
  }

  static const char* value(const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"DoDishesGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: tutorial_action/DoDishesGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"uint32 dish_id\n"
;
  }

  static const char* value(const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoDishesActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_action::DoDishesActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_action::DoDishesActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::tutorial_action::DoDishesGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_ACTION_MESSAGE_DODISHESACTIONGOAL_H
