// Auto-generated. Do not edit!

// (in-package tutorial_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoDishesGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dish_id = null;
    }
    else {
      if (initObj.hasOwnProperty('dish_id')) {
        this.dish_id = initObj.dish_id
      }
      else {
        this.dish_id = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoDishesGoal
    // Serialize message field [dish_id]
    bufferOffset = _serializer.uint32(obj.dish_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoDishesGoal
    let len;
    let data = new DoDishesGoal(null);
    // Deserialize message field [dish_id]
    data.dish_id = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'tutorial_action/DoDishesGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2a81404058645381c12ea9d0f83626d6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    uint32 dish_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoDishesGoal(null);
    if (msg.dish_id !== undefined) {
      resolved.dish_id = msg.dish_id;
    }
    else {
      resolved.dish_id = 0
    }

    return resolved;
    }
};

module.exports = DoDishesGoal;
