// Auto-generated. Do not edit!

// (in-package tutorial_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoDishesResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.total_is_washed = null;
    }
    else {
      if (initObj.hasOwnProperty('total_is_washed')) {
        this.total_is_washed = initObj.total_is_washed
      }
      else {
        this.total_is_washed = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoDishesResult
    // Serialize message field [total_is_washed]
    bufferOffset = _serializer.uint32(obj.total_is_washed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoDishesResult
    let len;
    let data = new DoDishesResult(null);
    // Deserialize message field [total_is_washed]
    data.total_is_washed = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'tutorial_action/DoDishesResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5b3bbd7ecb15f94222601861cfb31b9a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # resault
    uint32 total_is_washed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoDishesResult(null);
    if (msg.total_is_washed !== undefined) {
      resolved.total_is_washed = msg.total_is_washed;
    }
    else {
      resolved.total_is_washed = 0
    }

    return resolved;
    }
};

module.exports = DoDishesResult;
