// Auto-generated. Do not edit!

// (in-package tutorial_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoDishesFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.pecent_complete = null;
    }
    else {
      if (initObj.hasOwnProperty('pecent_complete')) {
        this.pecent_complete = initObj.pecent_complete
      }
      else {
        this.pecent_complete = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoDishesFeedback
    // Serialize message field [pecent_complete]
    bufferOffset = _serializer.uint32(obj.pecent_complete, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoDishesFeedback
    let len;
    let data = new DoDishesFeedback(null);
    // Deserialize message field [pecent_complete]
    data.pecent_complete = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'tutorial_action/DoDishesFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dfd0cf17f480a4264705c30ba0914c92';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback
    uint32 pecent_complete
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoDishesFeedback(null);
    if (msg.pecent_complete !== undefined) {
      resolved.pecent_complete = msg.pecent_complete;
    }
    else {
      resolved.pecent_complete = 0
    }

    return resolved;
    }
};

module.exports = DoDishesFeedback;
