; Auto-generated. Do not edit!


(cl:in-package tutorial_action-msg)


;//! \htmlinclude DoDishesFeedback.msg.html

(cl:defclass <DoDishesFeedback> (roslisp-msg-protocol:ros-message)
  ((pecent_complete
    :reader pecent_complete
    :initarg :pecent_complete
    :type cl:integer
    :initform 0))
)

(cl:defclass DoDishesFeedback (<DoDishesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoDishesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoDishesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial_action-msg:<DoDishesFeedback> is deprecated: use tutorial_action-msg:DoDishesFeedback instead.")))

(cl:ensure-generic-function 'pecent_complete-val :lambda-list '(m))
(cl:defmethod pecent_complete-val ((m <DoDishesFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial_action-msg:pecent_complete-val is deprecated.  Use tutorial_action-msg:pecent_complete instead.")
  (pecent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoDishesFeedback>) ostream)
  "Serializes a message object of type '<DoDishesFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'pecent_complete)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'pecent_complete)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'pecent_complete)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'pecent_complete)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoDishesFeedback>) istream)
  "Deserializes a message object of type '<DoDishesFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'pecent_complete)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'pecent_complete)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'pecent_complete)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'pecent_complete)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoDishesFeedback>)))
  "Returns string type for a message object of type '<DoDishesFeedback>"
  "tutorial_action/DoDishesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoDishesFeedback)))
  "Returns string type for a message object of type 'DoDishesFeedback"
  "tutorial_action/DoDishesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoDishesFeedback>)))
  "Returns md5sum for a message object of type '<DoDishesFeedback>"
  "dfd0cf17f480a4264705c30ba0914c92")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoDishesFeedback)))
  "Returns md5sum for a message object of type 'DoDishesFeedback"
  "dfd0cf17f480a4264705c30ba0914c92")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoDishesFeedback>)))
  "Returns full string definition for message of type '<DoDishesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%uint32 pecent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoDishesFeedback)))
  "Returns full string definition for message of type 'DoDishesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%uint32 pecent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoDishesFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoDishesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DoDishesFeedback
    (cl:cons ':pecent_complete (pecent_complete msg))
))
