; Auto-generated. Do not edit!


(cl:in-package tutorial_action-msg)


;//! \htmlinclude DoDishesResult.msg.html

(cl:defclass <DoDishesResult> (roslisp-msg-protocol:ros-message)
  ((total_is_washed
    :reader total_is_washed
    :initarg :total_is_washed
    :type cl:integer
    :initform 0))
)

(cl:defclass DoDishesResult (<DoDishesResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoDishesResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoDishesResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial_action-msg:<DoDishesResult> is deprecated: use tutorial_action-msg:DoDishesResult instead.")))

(cl:ensure-generic-function 'total_is_washed-val :lambda-list '(m))
(cl:defmethod total_is_washed-val ((m <DoDishesResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial_action-msg:total_is_washed-val is deprecated.  Use tutorial_action-msg:total_is_washed instead.")
  (total_is_washed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoDishesResult>) ostream)
  "Serializes a message object of type '<DoDishesResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_is_washed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_is_washed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_is_washed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_is_washed)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoDishesResult>) istream)
  "Deserializes a message object of type '<DoDishesResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_is_washed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_is_washed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_is_washed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_is_washed)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoDishesResult>)))
  "Returns string type for a message object of type '<DoDishesResult>"
  "tutorial_action/DoDishesResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoDishesResult)))
  "Returns string type for a message object of type 'DoDishesResult"
  "tutorial_action/DoDishesResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoDishesResult>)))
  "Returns md5sum for a message object of type '<DoDishesResult>"
  "5b3bbd7ecb15f94222601861cfb31b9a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoDishesResult)))
  "Returns md5sum for a message object of type 'DoDishesResult"
  "5b3bbd7ecb15f94222601861cfb31b9a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoDishesResult>)))
  "Returns full string definition for message of type '<DoDishesResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# resault~%uint32 total_is_washed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoDishesResult)))
  "Returns full string definition for message of type 'DoDishesResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# resault~%uint32 total_is_washed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoDishesResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoDishesResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DoDishesResult
    (cl:cons ':total_is_washed (total_is_washed msg))
))
