; Auto-generated. Do not edit!


(cl:in-package tutorial_action-msg)


;//! \htmlinclude DoDishesGoal.msg.html

(cl:defclass <DoDishesGoal> (roslisp-msg-protocol:ros-message)
  ((dish_id
    :reader dish_id
    :initarg :dish_id
    :type cl:integer
    :initform 0))
)

(cl:defclass DoDishesGoal (<DoDishesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoDishesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoDishesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tutorial_action-msg:<DoDishesGoal> is deprecated: use tutorial_action-msg:DoDishesGoal instead.")))

(cl:ensure-generic-function 'dish_id-val :lambda-list '(m))
(cl:defmethod dish_id-val ((m <DoDishesGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tutorial_action-msg:dish_id-val is deprecated.  Use tutorial_action-msg:dish_id instead.")
  (dish_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoDishesGoal>) ostream)
  "Serializes a message object of type '<DoDishesGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dish_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'dish_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'dish_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'dish_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoDishesGoal>) istream)
  "Deserializes a message object of type '<DoDishesGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dish_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'dish_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'dish_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'dish_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoDishesGoal>)))
  "Returns string type for a message object of type '<DoDishesGoal>"
  "tutorial_action/DoDishesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoDishesGoal)))
  "Returns string type for a message object of type 'DoDishesGoal"
  "tutorial_action/DoDishesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoDishesGoal>)))
  "Returns md5sum for a message object of type '<DoDishesGoal>"
  "2a81404058645381c12ea9d0f83626d6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoDishesGoal)))
  "Returns md5sum for a message object of type 'DoDishesGoal"
  "2a81404058645381c12ea9d0f83626d6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoDishesGoal>)))
  "Returns full string definition for message of type '<DoDishesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%uint32 dish_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoDishesGoal)))
  "Returns full string definition for message of type 'DoDishesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%uint32 dish_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoDishesGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoDishesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DoDishesGoal
    (cl:cons ':dish_id (dish_id msg))
))
